- name: Change Password
  hosts: exemplo # Informe host ou o grupo
  vars:
    # comando para crypt a senha
    # na familia DEB: mkpasswd -5 'senha'
    # na familia RMP: openssl passwd -1 'senha'
    password: $1$5n7z8Qo/$BTbwFo1kylmSW9KO/zFD51
  tasks:
    - name: Trocando senhas
      user:
        name: hostname # Informe o usuario
        password: "{{password}}"
        update_password: always
